server:
  port: 8000

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true